Move pypanda target test to last position because
because panda.shutdown() doesn't close the socket with panda-system-*
well.
Error: panda-system-arm: -qmp tcp:127.0.0.1:3334,server,nowait: Failed
to bind socket: Address already in use